# Generated by Django 2.1 on 2019-04-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255)),
                ('movie_details_page', models.CharField(blank=True, default='', max_length=255)),
                ('movie_released', models.BooleanField()),
                ('movie_release_date', models.IntegerField(blank=True)),
                ('movie_year', models.IntegerField(blank=True)),
                ('movie_month', models.IntegerField(blank=True)),
                ('movie_date', models.IntegerField(blank=True)),
                ('movie_audio', models.TextField(blank=True, default='', max_length=20)),
                ('movie_audio_hindi', models.BooleanField()),
                ('movie_audio_english', models.BooleanField()),
                ('movie_audio_dual', models.BooleanField()),
                ('movie_image_url', models.CharField(blank=True, default='', max_length=2083)),
                ('movie_quality', models.CharField(blank=True, default='', max_length=100)),
                ('movie_quality_hd', models.BooleanField()),
                ('movie_quality_sd', models.BooleanField()),
                ('movie_quality_cam', models.BooleanField()),
                ('movie_stars_in_movie', models.CharField(blank=True, default='', max_length=100)),
                ('movie_type', models.CharField(blank=True, default='', max_length=20)),
                ('movie_type_hindi', models.BooleanField()),
                ('movie_type_english', models.BooleanField()),
                ('movie_director', models.CharField(blank=True, default='', max_length=50)),
                ('movie_story_long', models.TextField(blank=True, default='', max_length=900000)),
                ('movie_story_short', models.TextField(blank=True, default='', max_length=5000)),
                ('movie_review', models.TextField(blank=True, default='', max_length=4000)),
                ('movie_rating', models.FloatField(blank=True)),
                ('movie_trailer', models.CharField(blank=True, default='', max_length=2083)),
                ('movie_download_link1_website', models.TextField(blank=True, default='', max_length=100)),
                ('movie_download_link1', models.CharField(blank=True, default='', max_length=2083)),
                ('movie_download_link1_adds', models.TextField(blank=True, default='', max_length=100)),
                ('movie_download_link2_website', models.TextField(blank=True, default='', max_length=100)),
                ('movie_download_link2', models.CharField(blank=True, default='', max_length=2083)),
                ('movie_download_link2_adds', models.TextField(blank=True, default='', max_length=100)),
                ('movie_download_link3_website', models.TextField(blank=True, default='', max_length=100)),
                ('movie_download_link3', models.CharField(blank=True, default='', max_length=2083)),
                ('movie_download_link3_adds', models.TextField(blank=True, default='', max_length=100)),
                ('movie_download_link4_website', models.TextField(blank=True, default='', max_length=100)),
                ('movie_download_link4', models.CharField(blank=True, default='', max_length=2083)),
                ('movie_download_link4_adds', models.TextField(blank=True, default='', max_length=100)),
                ('movie_download_link5_website', models.TextField(blank=True, default='', max_length=100)),
                ('movie_download_link5', models.CharField(blank=True, default='', max_length=2083)),
                ('movie_download_link5_adds', models.TextField(blank=True, default='', max_length=100)),
                ('movie_download_link6_website', models.TextField(blank=True, default='', max_length=100)),
                ('movie_download_link6', models.CharField(blank=True, default='', max_length=2083)),
                ('movie_download_link6_adds', models.TextField(blank=True, default='', max_length=100)),
                ('movie_download_link7_website', models.TextField(blank=True, default='', max_length=100)),
                ('movie_download_link7', models.CharField(blank=True, default='', max_length=2083)),
                ('movie_download_link7_adds', models.TextField(blank=True, default='', max_length=100)),
                ('movie_download_link8_website', models.TextField(blank=True, default='', max_length=100)),
                ('movie_download_link8', models.CharField(blank=True, default='', max_length=2083)),
                ('movie_download_link8_adds', models.TextField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
