# Generated by Django 2.1 on 2019-04-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviehome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='movie_audio_dual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='movie_audio_english',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='movie_audio_hindi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='movie_quality_cam',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='movie_quality_hd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='movie_quality_sd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='movie_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='movie_type_english',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='movie_type_hindi',
            field=models.BooleanField(default=False),
        ),
    ]
