# Generated by Django 2.1 on 2019-04-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviehome', '0002_auto_20190409_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='movie_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='movie_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='movie_release_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='movie_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
