# Generated by Django 2.1 on 2019-04-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviehome', '0003_auto_20190409_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='movie_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
