# Generated by Django 2.1 on 2019-04-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviehome', '0004_auto_20190409_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255)),
                ('movie_details_page', models.CharField(blank=True, default='', max_length=255)),
                ('movie_released', models.BooleanField(default=False)),
                ('movie_release_date', models.IntegerField(blank=True, null=True)),
                ('movie_year', models.IntegerField(blank=True, null=True)),
                ('movie_month', models.IntegerField(blank=True, null=True)),
                ('movie_date', models.IntegerField(blank=True, null=True)),
                ('movie_audio', models.TextField(blank=True, default='', max_length=20)),
                ('movie_audio_hindi', models.BooleanField(default=False)),
                ('movie_audio_english', models.BooleanField(default=False)),
                ('movie_audio_dual', models.BooleanField(default=False)),
                ('movie_image_url', models.CharField(blank=True, default='', max_length=2083)),
                ('movie_quality', models.CharField(blank=True, default='', max_length=100)),
                ('movie_quality_hd', models.BooleanField(default=False)),
                ('movie_quality_sd', models.BooleanField(default=False)),
                ('movie_quality_cam', models.BooleanField(default=False)),
                ('movie_stars_in_movie', models.CharField(blank=True, default='', max_length=100)),
                ('movie_type', models.CharField(blank=True, default='', max_length=20)),
                ('movie_type_hindi', models.BooleanField(default=False)),
                ('movie_type_english', models.BooleanField(default=False)),
                ('movie_director', models.CharField(blank=True, default='', max_length=50)),
                ('movie_story_long', models.TextField(blank=True, default='', max_length=900000)),
                ('movie_story_short', models.TextField(blank=True, default='', max_length=5000)),
                ('movie_review', models.TextField(blank=True, default='', max_length=4000)),
                ('movie_rating', models.FloatField(blank=True, null=True)),
                ('movie_trailer', models.CharField(blank=True, default='', max_length=2083)),
                ('movie_trailer2', models.CharField(blank=True, default='', max_length=2083)),
            ],
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='movie_trailer2',
            field=models.CharField(blank=True, default='', max_length=2083),
        ),
    ]
