# Generated by Django 2.1 on 2019-06-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviehome', '0006_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetails',
            name='movie_trailer_review',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
    ]
