# Generated by Django 2.1 on 2019-06-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviehome', '0007_moviedetails_movie_trailer_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingdetails',
            name='movie_audio',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
