# Generated by Django 2.1 on 2019-06-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviehome', '0008_auto_20190609_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetails',
            name='movie_stream_link1',
            field=models.CharField(blank=True, default='', max_length=2083),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='movie_stream_link1_website',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='movie_stream_link2',
            field=models.CharField(blank=True, default='', max_length=2083),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='movie_stream_link2_website',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='movie_stream_link3',
            field=models.CharField(blank=True, default='', max_length=2083),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='movie_stream_link3_website',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='movie_stream_link4',
            field=models.CharField(blank=True, default='', max_length=2083),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='movie_stream_link4_website',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='movie_stream_link5',
            field=models.CharField(blank=True, default='', max_length=2083),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='movie_stream_link5_website',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='movie_stream_link6',
            field=models.CharField(blank=True, default='', max_length=2083),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='movie_stream_link6_website',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='movie_stream_link7',
            field=models.CharField(blank=True, default='', max_length=2083),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='movie_stream_link7_website',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='movie_stream_link8',
            field=models.CharField(blank=True, default='', max_length=2083),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='movie_stream_link8_website',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
